---
# https://github.com/opendatahub-io/odh-manifests
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: newton-odh
  namespace: newton-odh
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  ## Seldon - subscribe to the Seldon operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odhseldon/cluster
    name: odhseldon
  ## Apache Superset
  # - kustomizeConfig:
  #     parameters:
  #     - name: SUPERSET_ADMIN_PASSWORD
  #       value: admin
  #     repoRef:
  #       name: manifests
  #       path: superset
  #   name: superset
  ## Kafka - subscribe to the Strimzi Operator
  # - kustomizeConfig:
  #     parameters:
  #     - name: namespace
  #       value: openshift-operators
  #     repoRef:
  #       name: manifests
  #       path: kafka/cluster
  #   name: strimzi-operator
  ## Kafka - deploy Kafka cluster
  # - kustomizeConfig:
  #     repoRef:
  #       name: manifests
  #       path: kafka/kafka
  #   name: kafka-cluster
  ## Grafana - subscribe to the Grafana Operator
  # - kustomizeConfig:
  #     repoRef:
  #       name: manifests
  #       path: grafana/cluster
  #   name: grafana-cluster
  ## Grafana - creates a grafana instance with a route
  # - kustomizeConfig:
  #     repoRef:
  #       name: manifests
  #       path: grafana/grafana
  #   name: grafana-instance
  ## Spark - subscribe to the Apache Spark Operator
  # - kustomizeConfig:
  #     repoRef:
  #       name: manifests
  #       path: radanalyticsio/spark/cluster
  #   name: radanalyticsio-spark-cluster
  ## Prometheus - subscribe to the prometheus operator
  # - kustomizeConfig:
  #     repoRef:
  #       name: manifests
  #       path: prometheus/cluster
  #   name: prometheus-cluster
  ## Prometheus - deploy a prometheus instance
  # - kustomizeConfig:
  #     repoRef:
  #       name: manifests
  #       path: prometheus/operator
  #   name: prometheus-operator
  ## JupyterHub - 
  - kustomizeConfig:
      parameters:
        - name: s3_endpoint_url
          value: "s3.odh.com"
      repoRef:
        name: manifests
        path: jupyterhub/jupyterhub
    name: jupyterhub
  ## Jupyter notebooks with additional overlays
  - kustomizeConfig:
      overlays:
      #- cuda-11.0.3
      - additional
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
    name: notebook-images
  ## Apache Airflow - subscribe to the Apache Airflow operator
  # - kustomizeConfig:
  #     repoRef:
  #       name: manifests
  #       path: airflow/operator
  #   name: airflow-operator
  ## Apache Airflow - instance of Apache Airflow
  # - kustomizeConfig:
  #     repoRef:
  #       name: manifests
  #       path: airflow/cluster
  #   name: airflow-cluster
  ## ODH Argo - subscription to Argo CD Operator
  # - kustomizeConfig:
  #     repoRef:
  #       name: manifests
  #       path: odhargo/cluster
  #   name: odhargo-cluster
  ## ODH Argo - instance of ArgoCD
  # - kustomizeConfig:
  #     repoRef:
  #       name: manifests
  #       path: odhargo/odhargo
  #   name: odhargo
  ## Model Mesh - instance of model mesh serving service
  # - kustomizeConfig:
  #     overlays:
  #       - odh-model-controller
  #     repoRef:
  #       name: manifests
  #       path: model-mesh
  #   name: model-mesh
  ## ODH Dashboard UI
  - kustomizeConfig:
      overlays:
      - authentication
      repoRef:
        name: manifests
        path: odh-dashboard
    name: odh-dashboard
  repos:
  - name: kf-manifests
    #uri: https://github.com/opendatahub-io/manifests/tarball/v1.4.0-rc.2-openshift
    uri: https://github.com/opendatahub-io/manifests/tarball/v1.5-branch-openshift
  - name: manifests
    uri: https://github.com/opendatahub-io/odh-manifests/tarball/master
    #uri: https://github.com/opendatahub-io/odh-manifests/tarball/v1.3
    #uri: https://github.com/opendatahub-io/manifests/archive/v1.5-branch-openshift.tar.gz
  # - name: newton
  #   uri: https://github.com/williamcaban/newton-stack/tarball/master
  #version: v1.5.0
  #version: master